from .HomeView import *
from .LoginView import *
from .PainelAdministradorView import *
from .PainelAdministradorDisciplinaView import *
from .PainelAdministradorCursoView import *
from .PainelAdministradorGrupoView import *
from .PainelAdministradorProfessorView import *
from .PainelAdministradorTurmaView import *
from .PainelAlunoView import *
from .PainelAlunoGrupoView import *
from .PainelProfessorView import *
from .PainelAdministradorPerfil import *