# Generated by Django 2.0.5 on 2018-06-01 23:25

import core.models.managers.UsuarioManager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'USUARIO',
            },
            managers=[
                ('objects', core.models.managers.UsuarioManager.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('semestres', models.IntegerField()),
            ],
            options={
                'db_table': 'CURSO',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=240)),
                ('sigla', models.CharField(max_length=5, unique=True)),
                ('cursos', models.ManyToManyField(blank=True, db_table='CURSO_DISICPLINAS', related_name='disciplinas', to='core.Curso')),
            ],
            options={
                'db_table': 'DISCIPLINA',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'GRUPO',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=15)),
                ('sigla', models.CharField(max_length=1)),
                ('ano', models.PositiveSmallIntegerField()),
                ('semestre', models.PositiveSmallIntegerField()),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.Curso')),
            ],
            options={
                'db_table': 'TURMA',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ADMINISTRADOR',
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.managers.UsuarioManager.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ra', models.IntegerField(unique=True, verbose_name='ra')),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'ALUNO',
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.managers.UsuarioManager.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'PROFESSOR',
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.managers.UsuarioManager.UsuarioManager()),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.Turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupos',
            field=models.ManyToManyField(blank=True, db_table='GRUPO_ALUNO', related_name='alunos', to='core.Grupo'),
        ),
    ]
