# Generated by Django 2.0.5 on 2018-05-13 15:42

import core.models.managers.UsuarioManager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180512_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ADMINISTRADOR',
            },
            bases=('core.usuario',),
            managers=[
                ('objects', core.models.managers.UsuarioManager.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='sigla',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
