# Generated by Django 2.0.5 on 2018-05-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180513_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='sigla',
        ),
    ]
