# Generated by Django 2.0.5 on 2018-05-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_grupo_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tema',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
