# Generated by Django 2.0.5 on 2018-05-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grupo_tema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='ra',
        ),
    ]
