# Generated by Django 2.0 on 2018-05-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180516_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='ra',
            field=models.IntegerField(default=1, unique=True, verbose_name='ra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grupo',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
    ]
